# Generated by Django 4.2.3 on 2023-08-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qiqicommandsmodel',
            old_name='mini-description',
            new_name='mini_description',
        ),
    ]
