# Generated by Django 4.2.3 on 2023-08-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_qiqicommandscategorymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QiqiCommandsCategoryModel',
            new_name='CommandsCategoryModel',
        ),
    ]
