# Generated by Django 4.2.3 on 2023-08-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0007_alter_commandscategorymodel_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandsCategoryModel',
            new_name='QiqiCommandsCategoryModel',
        ),
    ]
