# Generated by Django 4.2.4 on 2023-08-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qiqicommandsmodel',
            old_name='mini-description',
            new_name='mini_description',
        ),
    ]
