# Generated by Django 4.2.4 on 2023-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_mini_description_qiqicommandsmodel_mini_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiqicommandsmodel',
            name='mini_description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
